config/routes.rb
Rails.application.routes.draw do
  
    root 'gossips#index', as: 'index'
    
    resources :gossips    

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
      validates :anonymous_author, :content, presence: true,
                    length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
    def index
        @gossips = Gossip.all
    end

    def new
        @gossip = Gossip.new
    end
    
    def show
        @gossip = Gossip.find(params[:id])
    end
    
    def edit
        @gossip = Gossip.find(params[:id])
    end

    def create
        @gossip = Gossip.new(gossip_params)
        @gossip.save 
        render 'show'
    end
    
    def update
        @gossip = Gossip.find(params[:id])
        @gossip.update(gossip_params)
        @gossip.save
        render 'show'
    end
    
    def destroy
        @gossip = Gossip.find(params[:id])
        @gossip.destroy
        redirect_to index_path
    end
    
    private
    def gossip_params
        params.require(:gossip).permit(:anonymous_author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>

app/views/gossips/edit.html.erb
<h1>Gossips#edit</h1>
<style>
    
    input[type=string] {
        border: 1px black solid;
    }

</style>

<form action="/gossips/<%= @gossip.id %>" method="POST" accept-charset="UTF-8">
    
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
     <input type="hidden" name="_method" value="patch">
     
      Author: <br><input type="string" name="gossip[anonymous_author]"><br>
  
      Gossip: <br><input type="string" name="gossip[content]"><br>
      
      <br><input type="submit" value="Submit">
</form>

<%= link_to 'Gossips', controller: 'gossips' %>
 

app/views/gossips/index.html.erb
<h1>Gossips#index</h1>
<table>
  <tr>
    <th>Author</th>
    <th>Gossip</th>
  </tr>
 
  <% @gossips.each do |gossip| %>
    <tr>
      <td><%= gossip.anonymous_author %></td>
      <td><%= gossip.content %></td>
      <td><%= link_to 'Show', gossip_path(gossip) %></td>
      <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
      <td><%= link_to 'Destroy', gossip_path(gossip),
              method: :delete,
      data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
</table>

Menu : <%= link_to 'Gossips', controller: 'gossips' %> | <%= link_to 'New Gossip', new_gossip_path %>

app/views/gossips/new.html.erb
<h1>Gossips#new</h1>
<style>
    
    input[type=string] {
        border: 1px black solid;
    }

</style>

<form action="/gossips" method="POST" accept-charset="UTF-8">
    
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
     
      Author: <br><input type="string" name="gossip[anonymous_author]"><br>
  
      Gossip: <br><input type="string" name="gossip[content]"><br>
      
      <br><input type="submit" value="Submit">
</form>

<%= link_to 'Gossips', controller: 'gossips' %>
 

app/views/gossips/show.html.erb
<h1>Gossips#show</h1>
 <p>
  <strong>Author:</strong>
  <%= @gossip.anonymous_author %>
</p>
 
<p>
  <strong>Gossip:</strong>
  <%= @gossip.content %>
</p>


Menu : <%= link_to 'Gossips', controller: 'gossips' %> | <%= link_to 'New Gossip', new_gossip_path %>

app/views/gossips/update.html.erb
<h1>Gossips#create</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
    <link rel="stylesheet" href="//cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.1.1.min.css"/>
  </head>

  <body>
    <%= yield %>
  </body>
</html>